name: Sysdig Image Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  image-scan:
    runs-on: ubuntu-latest

    steps:
      - name: üõéÔ∏è Checkout code
        uses: actions/checkout@v3

      - name: üß± Build Docker images
        run: |
          docker build -t voting-app ./vote
          docker build -t worker ./worker
          docker build -t result ./result

      - name: üîç Scan with Sysdig (voting-app)
        run: |
          docker run --rm \
            --platform linux/amd64 \
            --user 0 \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -e SECURE_API_TOKEN="${{ secrets.SECURE_API_TOKEN }}" \
            quay.io/sysdig/sysdig-cli-scanner:1.22.4 \
              --apiurl https://app.au1.sysdig.com \
              --loglevel info \
              --skiptlsverify \
              docker://voting-app

      - name: üîç Scan with Sysdig (worker)
        run: |
          docker run --rm \
            --platform linux/amd64 \
            --user 0 \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -e SECURE_API_TOKEN="${{ secrets.SECURE_API_TOKEN }}" \
            quay.io/sysdig/sysdig-cli-scanner:1.22.4 \
              --apiurl https://app.au1.sysdig.com \
              --loglevel info \
              --skiptlsverify \
              docker://worker

      - name: üîç Scan with Sysdig (result)
        run: |
          docker run --rm \
            --platform linux/amd64 \
            --user 0 \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -e SECURE_API_TOKEN="${{ secrets.SECURE_API_TOKEN }}" \
            quay.io/sysdig/sysdig-cli-scanner:1.22.4 \
              --apiurl https://app.au1.sysdig.com \
              --loglevel info \
              --skiptlsverify \
              docker://result

